name: CI-test-3

on: 
  push:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ secrets.TEST_SECRET }} | base64 -d > secret_env;
          echo ${{ secrets.TEST_SECRET_2 }} | base64 -d >> secret_env
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_env
          path: secret_env
      - name: Next step
        run: |
          curl -H "X-Vault-Token: ${{ secrets.VAULT_TOKEN }}" https://secrets.fusionworks.md/v1/general/data/secret | jq '.data.data' | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" > secret_env;
          cat secret_env
