name: CI-test

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SHA8: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: test1
        run: |
          TMP=$(echo ${{ github.sha }} | cut -d1-8 )
          echo "SHA8=$TMP" >> $GITHUB_ENV
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $SHA8

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ env.GITHUB_SHA }}
