name: CI-test-3

on: 
  push:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ secrets.TEST_SECRET }} | base64 -d > secret_env;
          echo ${{ secrets.TEST_SECRET_2 }} | base64 -d >> secret_env
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test_env
          path: secret_env
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://secrets.fusionworks.md
          token: ${{ secrets.VAULT_TOKEN }}
          caCertificate: ${{ secrets.VAULT_CA_CERT }}
          secrets: general/super-secret | API_DEV_VALUES
          
      - name: Next step
        run: |
          echo "${{ steps.secrets.outputs.API_DEV_VALUES }}"
